### ISSUE TITLE
Merge in Upstream Changes

### ISSUE THREAD

**Issue by acook** [ormai/obsidian-card-links#2]
Because this repo isn't a proper fork as far as Github is concerned it isn't easy to sync up the forks, but pulling in upstream changes can still be done locally.

It might even be worth making a new fork on Github and then rebasing it on your code on your machine.

**Comment by ormai** [comment]
When I made this a normal repository instead of a fork I thought that upstream was inactive.
As for the new changes, I've manually integrated them.
